#!/usr/bin/env bash
# # After configuring domain zone, use this script to output where each subdomain points to

execDig () {
    domain=$2
    subdomain=$1

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

subdomains=( "wwww", "lb-01", "web-01", "web-02" )

if [ $# -eq 1 ]
then
    url="$1"
    for s in "${subdomains[@]}"
    do
        execDig "$s" "$url"
    done
elif [ $# -eq 2 ]
then
    url="$1"
    sub="$2"
    execDig "$sub" "$url"
fi