#!/bin/bash
# checks or updates snapd
# removes any non snap certbot installation
# installs cerbot, creates ans istalls a certificate

sudo snap install core; sudo snap refresh core
# Install Certbot
sudo snap install --classic certbot
# Prepare the Certbot command
sudo ln -s /snap/bin/certbot /usr/bin/certbot
# get and install your certificates...
sudo certbot --nginx

# Test automatic renewal
sudo certbot renew --dry-run