#!/usr/bin/env bash
# Install nginx on my web01 server
# Nginx should be listening on port 80
# When sent a GET request at root, return a page that contains at least
# one string "Hello World"

# install nginx
apt update
apt -y install nginx
# start nginx
service nginx start
# allow only http on port 80
ufw allow 'Nginx HTTP'
# file config
mkdir -p /var/www/html
chmod -R 775 /var/www
echo "Hello World!" > /var/www/html/index.html
# restart
service nginx restart