#!/usr/bin/env bash
# Install nginx on my web01 server
# Nginx should be listening on port 80
# When sent a GET request at root, return a page that contains at least
# one string "Hello World"

# install nginx
apt update
apt -y install nginx
# allow only http on port 80
sudo ufw allow 'Nginx HTTP'
# enable nginx
service nginx enable
service nginx start
# file config
sudo mkdir -p /var/www/html
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 775 /var/www
echo "Hello World!" > /var/www/html/index.html
# restart
service nginx restart