#!/usr/bin/env bash
# Install nginx on my web01 server
# Nginx should be listening on port 80
# When sent a GET request at root, return a page that contains at least
# one string "Hello World"
apt-get -y install nginx
service nginx start
echo "Hello World!" | tee /usr/share/nginx/html/index.html
