#!/usr/bin/env bash
apt-key add signature.key

sh -c 'echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7" >> /etc/apt/sources.list.d/mysql.list'

apt-get update

sudo apt-cache policy mysql-server

apt install -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*
